const fs = require('fs');
const path = require('path');

const configPath = path.join(__dirname, 'config.json');
const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));

const sites = config.sites.map(site => {
    // Destructure to remove automation-specific fields
    const { actions, keywords, timeout, ...siteConfig } = site;
    return siteConfig;
});

const output = {
    version: "1.0.0",
    description: "Generated by Automation",
    exportTime: new Date().toISOString(),
    sites: sites
};

const outputPath = path.join(__dirname, 'verified_sites.json');
fs.writeFileSync(outputPath, JSON.stringify(output, null, 2));
console.log(`Generated verified sites config at: ${outputPath}`);
